name: qoot
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  intl_utils: ^2.8.12
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FAFAFA"
  image: assets/master/light_splash_screen.png
  color_dark: "#077734"
  image_dark: assets/master/dark_splash_screen.png
  android_12:
    image: assets/master/light_splash_screen.png
    color: "#FAFAFA"
    image_dark: assets/master/dark_splash_screen.png
    color_dark: "#077734"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/master/
    - assets/fonts/
    - assets/fonts/cairo/
    - assets/animations/
    - assets/placeholder/

  fonts:
    - family: "Cairo"
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
